server:
    port: 8080

spring:
    application:
        name: lanchonete-gateway
    cloud:
        gateway:
            routes:
            - id: pedido-app
              uri:  http://svc-pedido-app
              predicates:
                - Path=/pedido-app/v3/api-docs, /pedido-app/**
            - id: producao-app
              uri:  http://svc-producao-app
              predicates:
                - Path=/producao-app/v3/api-docs, /producao-app/**
            - id: pagamento-app
              uri:  http://svc-pagamento-app
              predicates:
                - Path=/pagamento-app/v3/api-docs, /pagamento-app/**
        discovery:
            enabled: true
    main:
        web-application-type: reactive

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /pedido-app/v3/api-docs
        name: Pedido API
      - url: /producao-app/v3/api-docs
        name: Produção API
      - url: /pagamento-app/v3/api-docs
        name: Pagamento API
   
        