apiVersion: v1
kind: Service
metadata:
  name: svc-lanchonete-gateway-app
spec:
  selector:
    app: app-lanchonete-gateway-pod
  #type: NodePort
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30082

# Alterar o type para LoadBalancer para rodar no eks
# Alterar o type para NodePort para rodar no locahost
  